# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wips < Formula
  desc "wips-cli is a command line tool for tracking your daily work."
  homepage "https://github.com/rynskrmt/wips-cli"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.1.0/wips-cli_Darwin_x86_64.tar.gz"
      sha256 "eea7c4aa5d074959330502722fb5790d6c5f21f7dd29f2051819d46ca747a0bd"

      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.1.0/wips-cli_Darwin_arm64.tar.gz"
      sha256 "2c6d75d4dca2c7e58d93ef709b5583fb149abbe65b2b52ebd3cd84eaa7fc0677"

      def install
        bin.install "wip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.1.0/wips-cli_Linux_x86_64.tar.gz"
      sha256 "85c32d471eb41aacb97434c28dab271472c3a47d9bf2e0b96c907ea4f5ea0122"
      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.1.0/wips-cli_Linux_arm64.tar.gz"
      sha256 "3df96febf7dc89f3eeda2dc3633506ed8b956acb7bae2b41635b3bb08f4979a4"
      def install
        bin.install "wip"
      end
    end
  end

  test do
    system "#{bin}/wip --version"
  end
end
