# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Wips < Formula
  desc "wips-cli is a command line tool for tracking your daily work."
  homepage "https://github.com/rynskrmt/wips-cli"
  version "0.0.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.8/wips-cli_Darwin_x86_64.tar.gz"
      sha256 "f9c5ae4c2ce9a30cc6ff59b7af47f58112e7b0eb19f374bf5dba6f8608c15949"

      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.8/wips-cli_Darwin_arm64.tar.gz"
      sha256 "77133f3af52321cb52aa97ef497c7bab2dc6abc9200dbd898ba89a3589d3fca1"

      def install
        bin.install "wip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.8/wips-cli_Linux_x86_64.tar.gz"
      sha256 "b069042219c7b8e993172daca3afcc43b14fc9c6dcddf3b22a931dbaa5cdf3fb"
      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.8/wips-cli_Linux_arm64.tar.gz"
      sha256 "7bb7167a0692a5d580bae4adac358b4a7160eaf7e40c076a12709b01096960e2"
      def install
        bin.install "wip"
      end
    end
  end

  test do
    system "#{bin}/wip --version"
  end
end
