# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WipsCli < Formula
  desc "wips-cli is a command line tool for tracking your daily work."
  homepage "https://github.com/rynskrmt/wips-cli"
  version "0.0.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.5/wips-cli_Darwin_x86_64.tar.gz"
      sha256 "dae04a169b641732d323169ea6e9888fd8ee6b6782d2af2a1729c185c4cf63b9"

      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.5/wips-cli_Darwin_arm64.tar.gz"
      sha256 "34dd466373f675f71eb698bf0cdf3a66e4942beba1771fcc873f58e5125a7cd6"

      def install
        bin.install "wip"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.5/wips-cli_Linux_x86_64.tar.gz"
      sha256 "c0399aa8f1480e4d5d8dad5c62210f4fd407928221520ac1ebe0070a4698291e"
      def install
        bin.install "wip"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rynskrmt/wips-cli/releases/download/v0.0.5/wips-cli_Linux_arm64.tar.gz"
      sha256 "bcaa2c5af4dd28709976272ed99de2be7ed09f78f9b3344e11e60b544be01489"
      def install
        bin.install "wip"
      end
    end
  end

  test do
    system "#{bin}/wip --version"
  end
end
